language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t qroux/docker-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true qroux/docker-travis npm run test -- --coverage
